# Generated by Django 4.1.5 on 2023-01-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_age_user_username_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Role'),
        ),
    ]
