# Generated by Django 4.1.5 on 2023-01-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(auto_now=True, null=True, verbose_name='Date Of Birth'),
        ),
    ]
